name: master

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: "deploy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - uses: chrislennon/action-aws-cli@1.1
      - name: "Deploy to s3"
        run: |
          aws s3 sync . s3://${AWS_S3_BUCKET} --delete
        env:
          SOURCE_DIR: "."
          AWS_REGION: "us-east-1"
          AWS_S3_BUCKET: "${{ secrets.AWS_S3_BUCKET }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: "Send chanchan.io CloudFront invalidations"
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${DISTRIBUTION_ID} \
            --paths "/*"
        env:
          DISTRIBUTION_ID: "${{ secrets.DISTRIBUTION_ID }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
